#!/usr/bin/env php
<?php

declare(strict_types=1);

require __DIR__ . '/bootstrap/autoload.php';

use Marko\Cli\CliKernel;
use Marko\Cli\ProjectFinder;

$projectFinder = new ProjectFinder();

exit((new CliKernel(
    projectFinder: $projectFinder,
))->run($argv));
